mysql-server:
  hostname: mysql-server
  container_name: mysql-server
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql_mode="no_engine_substitution"
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=sequelize_demo
  ports:
    - '3306:3306'
